### ISSUE TITLE
stream

### ISSUE THREAD

**Issue by fresh08** [facebook/360-Capture-SDK#1]
Can this sdk privides push stream when Unity running and encoding? Thanks

**Comment by grancia** [comment]
Hi,

It's in our roadmap and will probably be launched in 1H 2017.

Thank you,

나의 iPhone에서 보냄

2017. 4. 20. 오전 12:03 fresh08 <notifications@github.com<mailto:notifications@github.com>> 작성:


Can this sdk privides push stream when Unity running and encoding? Thanks

**Comment by cg439** [comment]
This exists in latest SDK, closing
