### ISSUE TITLE
startEncoding function not found

### ISSUE THREAD

**Issue by mateicanavra** [facebook/360-Capture-SDK#10]
Any suggestions on properly importing the HWEncoder.dll? I have it in Assets/Plugins/x86_64

When I start encoding, I get the error below

```
EntryPointNotFoundException: startEncoding
FBCapture.SurroundCapture.Update () (at Assets/EncodePackage/Script/SurroundCapture.cs:221)
```

**Comment by cg439** [comment]
Can you share your project set up? We haven't seen this in other attempts that imported the HWEncoder

**Comment by mateicanavra** [comment]
Solved the issue. It was a matter of starting fresh and copy/pasting the HW encoder dll & .meta file from the demo folder directly into my project. Then adding the Encoder object
