### ISSUE TITLE
Only record video does not record audio

### ISSUE THREAD

**Issue by fresh08** [facebook/360-Capture-SDK#12]
HI:
I just want to record a h264 video file without recording the sound. But when I close the recording of audio-related code, has been reported "Failed to ascend out of a chunk in a RIFF file" error. The background may still record sound. How do i close recording related code?
Thank you.

**Comment by grancia** [comment]
Because it has been about over two months since v2.0 was released, I want to close v1.x related issues now. If you have any issue on v2.0, please create separate thread. 
Thanks,
