### ISSUE TITLE
Files not converting to mp4, not muxed

### ISSUE THREAD

**Issue by glitchersgames** [facebook/360-Capture-SDK#14]
I have had success recording video at 2048x1024 but increasing the resolution 7168x3584 causes a problem.

The files generated are the .wav and .h264 files with a size of 0 bytes. If I also stop the editor after stopping the recording it has an error about the render target being released is the camera's `targetTexture`.

I don't get any errors in the console, and have tried leaving the editor running after stopping the recording but the files remain.

**Comment by cg439** [comment]
That resolution seems really high and may be related to the underlying encoding API used, what hardware are you using? Have you tried a different resolution like 4096x2048 or 3840x1920?

**Comment by grancia** [comment]
Please check nVidia or AMD video encoding SDK site. 
For now maximum resolution is 4K with most of modern GPUs and H.264. 
https://developer.nvidia.com/nvidia-video-codec-sdk

**Comment by glitchersgames** [comment]
4096x2048 work for recording video.

I was trying to use it to record videos for YouTube as they recommend 7168 or higher - https://support.google.com/youtube/answer/6178631?hl=en

**Comment by cg439** [comment]
You should be ok with 4K. Most devices won't be able to play above 4K aside
from some desktop devices.

**Comment by cg439** [comment]
Closing issue as related to encoding SDK, unlikely we'll change this in short term, but something to keep in mind as a feature request for higher resolutions
