### ISSUE TITLE
Bitrate is low

### ISSUE THREAD

**Issue by MosheBenZacharia** [facebook/360-Capture-SDK#15]
Are there plans to allow for higher bitrate in a setting?

The current output has really low bitrate and the compression artifacts are extremely noticeable.

**Comment by cg439** [comment]
I think we can make it configurable since the encoding sdk can set bitrate
to encode at. Can you share some samples with artifacts, the bitrates  you
are seeing, and confirm how you are viewing this? We've uploaded 4K
video samples to fb and haven't noticed artifacts

**Comment by MosheBenZacharia** [comment]
Hey,

That would be great if it could be configurable.

I uploaded two samples to Google Driver here:
Non-Surround https://drive.google.com/open?id=0Bzu3m70ipHP1SUI4bHZSOVF0Y2s
Surround https://drive.google.com/open?id=0Bzu3m70ipHP1ZkRfQmlETmNrM1k

The non-surround video was recorded at 4096x2048, the bitrate I'm seeing is 4175.7kbps, which is exceptionally low for a video at that resolution. You can see a lot of compression artifacts and blockiness throughout the video.

The surround video was also recorded at 4096x2048, the bitrate I'm seeing is 3134.9kbps, which is far below the recommended bitrate for 360 videos.

I viewed the video and bitrate with MPlayerX and double checked with FFProbe.

-Mo

**Comment by MosheBenZacharia** [comment]
Any idea when we will see an update with a bitrate option? This is holding back an important video we're working on.

**Comment by cg439** [comment]
Can you shoot me an email at cpgupta@fb.com with specific details of the project? We may be able to give you an updated version that has a higher preset bitrate depending what your timeline needs look like (ahead of when we'd be able to merge that upstream to the main github repo).

We're working on exposing our native DLL code so you can modify the relevant section yourself

**Comment by MosheBenZacharia** [comment]
Sounds great, email sent!

**Comment by cg439** [comment]
Solution found, need to figure out timing to merge upstream to main repo code

**Comment by MosheBenZacharia** [comment]
Hi Cg439,

Is there any idea of when this will go live?

**Comment by Lobotomook** [comment]
Any updates on manual updating the bitrate? A higher bitrate would be pretty huge for the project I'm currently working on. Loving the SDK, doing everything else I need it to.

**Comment by cg439** [comment]
I think this should be live now?

**Comment by grancia** [comment]
You should be able to manage the bitrate now.
Check it with latest version.
Thanks,
