### ISSUE TITLE
Sample integration doesn't work | Unity 5.6.2f1

### ISSUE THREAD

**Issue by LukeNzk** [facebook/360-Capture-SDK#17]
I tried to open sample integration. It calls start/stopEncoding functions and muxing after stopEncoding but no video is saved. I tried different output paths and both surround and non-surround capturing. No errors logged, only information that the encoding started and stopped. Screenshots work.

**Comment by cg439** [comment]
What hardware are you using?

**Comment by poke50uk** [comment]
![pasted image at 2017_07_20 05_58 pm](https://user-images.githubusercontent.com/12011520/28429642-46880312-6d75-11e7-8cc9-9bbb677e6ade.png)

Sample doesn't work on 2017 branch either.

**Comment by grancia** [comment]
Because it has been about over two months since v2.0 was released, I want to close v1.x related issues now. If you have any issue on v2.0, please create separate thread. 
Thanks,
