### ISSUE TITLE
Is this plugin support windows 32 bit?

### ISSUE THREAD

**Issue by usunyu** [facebook/360-Capture-SDK#18]
In sample, I only see x86_64 plugin folder, no x86 folder, does it support 32 bit application?

**Comment by grancia** [comment]
Really sorry for belated answer.
Unfortunately, we only support 64bit now.

**Comment by cg439** [comment]
We're hoping to investigate what's required for 32 bit support next year in Jan/Feb

**Comment by cg439** [comment]
We now have a 32 bit dll though we haven't had a chance to test it. @grancia can share soon the DLL

**Comment by grancia** [comment]
I did test on my side, but I want to release it after having more test on different environment.

**Comment by grancia** [comment]
32bit plugin was released with v2.0.
Please have a test with the latest version. 
Thanks
