### ISSUE TITLE
Missing Scripts on Prefabs

### ISSUE THREAD

**Issue by mantalayer** [facebook/360-Capture-SDK#19]
I'm downloading as a zip from the master branch, and when I import that into Unity, the only Unity specific thing I can find is a prefab with a camera on it and 3 missing scripts. What scripts are these supposed to be? Any help would be extremely appreciated.

Thanks!

**Comment by vadimFRG** [comment]
I've had a very same issue after downloading. And much more after that while trying to make the SDK work with a simple project. Lates commit is bad, and a lot of stuff is broken or missing. A simple fix was to revert to commit before that or download that zip file instead.

**Comment by grancia** [comment]
Because it has been about over two months since v2.0 was released, I want to close v1.x related issues now. If you have any issue on v2.0, please create separate thread. 
Thanks,
