### ISSUE TITLE
Unity UI elements are not displayed

### ISSUE THREAD

**Issue by Creepymulder** [facebook/360-Capture-SDK#2]
Hi there,

I've noticed that Unity UI elements are not visible on capture (pictures and videos). You can easily reproduce the issue on the demo scene : The green circle around the tank is not visible on capture. For some reason it does work for non surround capture.

Thanks !

**Comment by fresh08** [comment]
Make sure your UI could be seen in the recording camera view.

**Comment by Creepymulder** [comment]
I can see the UI in the preview window of the recording camera if that's what you're talking about.

**Comment by fresh08** [comment]
What's unity version do you using, as far as I konwn, Unity 5.4.x has some bugs with UI rendering to Camera.

**Comment by Creepymulder** [comment]
I'm using Unity 5.5.2f1. Are you able to reproduce the issue on the demo scene with the green circle around the tank ? 

(Thanks for digging the issue btw :>)

**Comment by fresh08** [comment]
I paste you some images, if your still have trouble with it, I can your my project.
![qq 20170424211514](https://cloud.githubusercontent.com/assets/13703811/25338897/61ddd6d6-2933-11e7-8986-4d5ec379d2b2.jpg)
![qq 20170424211524](https://cloud.githubusercontent.com/assets/13703811/25338901/62c4aa34-2933-11e7-9056-f2d0bfba4f66.jpg)
![qq 20170424211535](https://cloud.githubusercontent.com/assets/13703811/25338902/63fe47f2-2933-11e7-8e19-076758c68d1d.jpg)

**Comment by Creepymulder** [comment]
Still having issues yes, here's when I take a "surround" screenshot, and a video, of the default scene, you can notice the green circle is missing around the tank on both capture : 

![screenshot_2048x1024_2017-04-24 03_22_56](https://cloud.githubusercontent.com/assets/5516779/25339197/1d693c6a-2902-11e7-942d-7f385d4bff12.jpg)

![untitled](https://cloud.githubusercontent.com/assets/5516779/25339296/7ead214e-2902-11e7-8789-3370852cf8e8.png)

What Unity version are you using ? I wouldn't mind getting your project for further testing.

**Comment by fresh08** [comment]
All right, I'm using Unity5.5.1 for test. I'll send your a github url of my testing project tommorw。

**Comment by Creepymulder** [comment]
Thanks ! I also tested on the latest stable version (5.6.0f3) and had the same issue.

**Comment by fresh08** [comment]
Hello, this is my testing project "https://github.com/fresh08/Unity_Test", you can download it for test.

**Comment by Creepymulder** [comment]
Thanks for your project, I've opened it on my Unity 5.5.2 and had the exact same issue with the UIs, I couldn't see the button you've set up.

Are you sure you're taking surround screenshot when pressing F1 ? From what I can tell from the pictures you've pasted here, those are non-surround capture.

**Comment by fresh08** [comment]
Sorry, I just test for non-surround model. I'll test in surround later.

**Comment by grancia** [comment]
Hi,

This is known issue in Unity when using “Camera.RenderToCubemap()”.
https://feedback.unity3d.com/suggestions/support-for-world-space-ui-elements-in-rendertocubemap

I will also start to talk with Unity.
Thank you,

**Comment by Creepymulder** [comment]
Well, that settles it, thanks for bringing this up, hopefully you'll find a workaround or they'll fix it soon enough !

**Comment by MosheBenZacharia** [comment]
Hello,

Was there any response from Unity on this issue? This is a pretty unfortunate bug.

**Comment by grancia** [comment]
It's still happening now unfortunately.... 
I really hope Unity fix the issue soon. You might also can push Unity team. :)
In the meantime, you probably can consider using other UI solution like Snap UI.
Sorry for the issue.

**Comment by vonengel3d** [comment]
I just ran in the exact same issue. Any update on this?

**Comment by vonengel3d** [comment]
@grancia The workaround script you mentioned in this script partly worked for me.
