### ISSUE TITLE
Broken Commit

### ISSUE THREAD

**Issue by vadimFRG** [facebook/360-Capture-SDK#20]
Hello, 

Trying to work with your SDK ran into a number of issues so far: 

1. Latest commit left HEAD in a broken state. 
        a. Unity Prefabs have missing links(easy to fix)
        b. No DLLs, no way of building them(solution doesn't compile) 
2. Had to revert checkout to commit before: 
        a. Everything seems to be normal there, but unfortunately, there is no x64 DLL and when I try to 
            build it with the solution provided, a solution would not build due to librtmp.lib file being 
            corrupt.

Dear developer, can you please fix the issues? I'm aiming to use this SDK with our in-house project.
Thanks, 
Vadim @ Free Range

**Comment by cg439** [comment]
Do you still see this issue?

**Comment by grancia** [comment]
Because it has been about over two months since v2.0 was released, I want to close v1.x related issues now. If you have any issue on v2.0, please create separate thread. 
Thanks,
