### ISSUE TITLE
Can I use 360-Capture-SDK in iOS app?

### ISSUE THREAD

**Issue by VictorZhang2014** [facebook/360-Capture-SDK#21]
I want to use 360 videos or photos in my iOS app, just like these videos on Facebook homepage, does it support?

**Comment by grancia** [comment]
The capture SDK generates typical 360 photos or videos. It means you can use them in your iOS app. 
But you can't integrate the SDK into your iOS app as it only supports PC GPU now. You can only use generated photos and videos in your iOS app.

**Comment by VictorZhang2014** [comment]
But how can I use the generated photos or videos in my iOS app? Any documentation?  Or where are the generated photos and videos what I can see or download?

**Comment by grancia** [comment]
You can set save folder path in unity script. But you should know it only work on PC environment. 
if you want to use it on iOS, you will need to find a way for copying the media files into your iOS.  The capture SDK is generating mp4(video capture) and jpg(photo capture).

**Comment by VictorZhang2014** [comment]
So what I concluded is that 360-Capture is unmatured in mobile environment, and whatever the resources are!

**Comment by cg439** [comment]
Yes, essentially, you can use the capture script and shaders for rendering out a texture that is equirectangular for 360 photos or videos, but you'd need to write native code or use a unity library for iOS that handles compressing/encoding the media content, saving to disk, and dealing with performance/threading constraints

**Comment by VictorZhang2014** [comment]
Got it. Thank you~ I won't take 360-video as a feature in my app for now, maybe I'll use in the future.
