### ISSUE TITLE
prefab issue and small bug

### ISSUE THREAD

**Issue by rms80** [facebook/360-Capture-SDK#23]
This is an amazing component - thank you!! I used previous versions to capture great videos of VR 3D interaction: https://www.youtube.com/watch?v=0PtXAfWaZ3g

However with the current version, I found two small problems when trying to set up my own Unity project to use EncodePackage, that prevent non-surround capturing from working (it didn't work in the included Unity demo, either)

1) the EncoderObject prefab does not have the FlippingTexture shader assigned. Can be fixed by assigning this shader in an instance of the prefab and clicking Apply in Inspector.

2) If you start w/ Do Surround Capture un-checked, and try to non-surround capture, there are errors in the log about a null render texture. This is because CaptureOptions.nonSurroundCapture.enabled is never set to true. This is my fix:
https://github.com/rms80/360-Capture-SDK/commit/7c0475cd0c9244e3efba88b2fefeca32219f8a43

**Comment by cg439** [comment]
Thanks for the heads up, would you mind submitting a pull request with your fix?

**Comment by grancia** [comment]
Because it has been about over two months since v2.0 was released, I want to close v1.x related issues now. If you have any issue on v2.0, please create separate thread. 
Thanks,
