### ISSUE TITLE
opengl support？

### ISSUE THREAD

**Issue by swq0553** [facebook/360-Capture-SDK#24]
When to support opengl application？

**Comment by cg439** [comment]
Do you mean having the code support openGL textures or a sample showing how to integrate the SDK into a native engine/non-Unity game that is using openGL?

**Comment by swq0553** [comment]
@cg439 yes，I want to use it in my engine which used opengl.

**Comment by grancia** [comment]
Sorry for belated answer.... 
We don't have plan for opengl support yet. If we have any update on it, we will post here. Thank you.

**Comment by swq0553** [comment]
@grancia ok
