### ISSUE TITLE
Sync issue

### ISSUE THREAD

**Issue by fresh08** [facebook/360-Capture-SDK#3]

**Comment by fresh08** [comment]
Hello, I meet a import issue that video not sync with audio。My app's fps about 60fps, it's far greater than 30. My testing method is play a movie in Unity and encoding it.
Best regards.

**Comment by grancia** [comment]
Hi,

Could you provide simple repro sample?
Thank you,

**Comment by fresh08** [comment]
https://raw.githubusercontent.com/fresh08/Unity_Test/master/360-Capture-SDK-Unity/Gallery/movie_2560x1440_2017-04-26%2002_09_46.mp4
This is my test project generated mp4 file, in front of a few seconds of audio and video is synchronized, the back is not synchronized. This is the git address of the project, (https://github.com/fresh08/Unity_Test), the test scene is SyncDemo.unity.
Thank you.

**Comment by grancia** [comment]
In your case, it can be fixed with adjusting videoFPS value in SurroundCapture.cs/NonSurroundCapture.cs as below. 
 int videoFPS = 27;  

But we will investigate more why sync issue is happening with default value.

**Comment by hhprg** [comment]
I believe this code in SurroundCapture.Update is the culprit:
`         if (fpsTimer >= fps)
         {
            fpsTimer = 0.0f;
`

It makes the audio and video gradually drift out of sync. Replacing it with this code appears to fix the problem:
`         if (fpsTimer >= fps)
         {
            fpsTimer -= fps;
`

**Comment by fresh08** [comment]
No, this can not solve the problem of audio and video synchronization. @hhprg

**Comment by fresh08** [comment]
Well, it seems to be synchronous, but I do not know how it works. @hhprg

**Comment by grancia** [comment]
Because it has been about over two months since v2.0 was released, I want to close v1.x related issues now. If you have any issue on v2.0, please create separate thread. 
Thanks,
