### ISSUE TITLE
Example Unity Project broken in Unity 2017.3

### ISSUE THREAD

**Issue by NoxMortem** [facebook/360-Capture-SDK#31]
As posted in https://github.com/facebook/360-Capture-SDK/issues/30
the library does not work at all and even If I open the Sample Project from master it does not do anything

This are the errors from the FBCaptureSDK
```
[ 2018-01-02 20:30:29 ][LOG]: Folder is already existed
[ 2018-01-02 20:30:29 ][ERROR]: Invalid render texture pointer(null)
[ 2018-01-02 20:31:07 ][ERROR]: Invalid render texture pointer(null)
```
Win 10 x64 Educational
Nvidia Geforce 1080 TI

![grafik](https://user-images.githubusercontent.com/6750572/34497069-34ab2606-effc-11e7-8a82-76954b1d96d7.png)

**Comment by rms80** [comment]
I think what I described here might fix this problem: https://github.com/facebook/360-Capture-SDK/issues/23

(have not managed to put together a PR yet)

**Comment by NoxMortem** [comment]
@rms80 Thanks for the heads-up we will definetly try this!

**Comment by grancia** [comment]
Because it has been about 2 months since v2.0 was released, I want to close v1.x related issues now. If you have any issue on v2.0, please create separate thread. 
Thanks,
