### ISSUE TITLE
mp4 output

### ISSUE THREAD

**Issue by haitheredavid** [facebook/360-Capture-SDK#33]
Thanks for the dopeness! I am trying to have my render output go to .mp4 but it only seems to only go to .h264 and .aac... is there something I'm missing? After a rendering there is an Error Type: 315

**Comment by grancia** [comment]
Can you check "FBCaptureSDK.txt" log file?

**Comment by haitheredavid** [comment]
Pew pew. Im using the Vive as my other camera, is it possible that the mic is trying to pick that audio?

[ 2018-02-05 15:17:00 ][INFO]: Released wave file resources
[ 2018-02-05 15:17:00 ][INFO]: Audio transcoding. Source file name ==================> : C:\Users\dmorgan\Desktop\Unity\parametricdesign\Gallery/movie_2048x1024_2018-02-05 03_16_57.wav
[ 2018-02-05 15:17:00 ][ERROR]: Failed to set pcm media type. [Error code] : -2147024809

**Comment by grancia** [comment]
Can you share full log?

**Comment by haitheredavid** [comment]
[ 2018-02-05 12:48:42 ][INFO]: Folder is already existed
[ 2018-02-05 12:48:42 ][INFO]: Set encode configurations successfully
[ 2018-02-05 12:48:42 ][INFO]: Audio device name: : Microphone (HTC Vive)
[ 2018-02-05 12:48:42 ][INFO]: Can't find VR audio devices. Just use default audio input and output
[ 2018-02-05 12:48:42 ][INFO]: WAV file name ==================> : C:\Users\dmorgan\Desktop\Unity\parametricdesign\Gallery/movie_2048x1024_2018-02-05 12_48_42.wav
[ 2018-02-05 12:48:42 ][INFO]: No data can be read from Microphone--IAudioCaptureClient::GetBuffer
[ 2018-02-05 12:48:42 ][INFO]: No data can be read from Microphone--IAudioCaptureClient::GetBuffer
[ 2018-02-05 12:48:45 ][INFO]: No data can be read from Microphone--IAudioCaptureClient::GetBuffer
[ 2018-02-05 12:49:17 ][INFO]: Released wave file resources
[ 2018-02-05 12:49:17 ][INFO]: Audio transcoding. Source file name ==================> : C:\Users\dmorgan\Desktop\Unity\parametricdesign\Gallery/movie_2048x1024_2018-02-05 12_48_42.wav
[ 2018-02-05 12:49:17 ][ERROR]: Failed to set pcm media type. [Error code] : -1072868846
[ 2018-02-05 13:06:38 ][INFO]: Folder is already existed
[ 2018-02-05 13:06:38 ][INFO]: Set encode configurations successfully
[ 2018-02-05 13:06:38 ][INFO]: WAV file name ==================> : C:\Users\dmorgan\Desktop\Unity\parametricdesign\Gallery/movie_2048x1024_2018-02-05 01_06_38.wav
[ 2018-02-05 13:06:38 ][INFO]: No data can be read from Microphone--IAudioCaptureClient::GetBuffer
[ 2018-02-05 13:08:19 ][INFO]: Released wave file resources
[ 2018-02-05 13:08:19 ][INFO]: Audio transcoding. Source file name ==================> : C:\Users\dmorgan\Desktop\Unity\parametricdesign\Gallery/movie_2048x1024_2018-02-05 01_06_38.wav
[ 2018-02-05 13:08:19 ][ERROR]: Failed to set pcm media type. [Error code] : -2147024809
[ 2018-02-05 14:17:48 ][INFO]: Folder is already existed
[ 2018-02-05 14:17:48 ][INFO]: Set encode configurations successfully
[ 2018-02-05 14:17:48 ][INFO]: WAV file name ==================> : C:\Users\dmorgan\Desktop\Unity\parametricdesign\Gallery/movie_2048x1024_2018-02-05 02_17_47.wav
[ 2018-02-05 14:17:49 ][INFO]: No data can be read from Microphone--IAudioCaptureClient::GetBuffer
[ 2018-02-05 14:18:40 ][INFO]: Released wave file resources
[ 2018-02-05 14:19:23 ][INFO]: Folder is already existed
[ 2018-02-05 14:19:23 ][INFO]: Set encode configurations successfully
[ 2018-02-05 14:19:23 ][INFO]: WAV file name ==================> : C:\Users\dmorgan\Desktop\Unity\parametricdesign\Gallery/movie_2048x1024_2018-02-05 02_19_23.wav
[ 2018-02-05 14:19:25 ][INFO]: No data can be read from Microphone--IAudioCaptureClient::GetBuffer
[ 2018-02-05 14:20:07 ][INFO]: No data can be read from Microphone--IAudioCaptureClient::GetBuffer
[ 2018-02-05 14:20:19 ][INFO]: Released wave file resources
[ 2018-02-05 14:20:19 ][INFO]: Audio transcoding. Source file name ==================> : C:\Users\dmorgan\Desktop\Unity\parametricdesign\Gallery/movie_2048x1024_2018-02-05 02_19_23.wav
[ 2018-02-05 14:20:20 ][ERROR]: Failed to set pcm media type. [Error code] : -2147024809
[ 2018-02-05 15:16:57 ][INFO]: Folder is already existed
[ 2018-02-05 15:16:57 ][INFO]: Set encode configurations successfully
[ 2018-02-05 15:16:57 ][INFO]: WAV file name ==================> : C:\Users\dmorgan\Desktop\Unity\parametricdesign\Gallery/movie_2048x1024_2018-02-05 03_16_57.wav
[ 2018-02-05 15:16:57 ][INFO]: No data can be read from Microphone--IAudioCaptureClient::GetBuffer
[ 2018-02-05 15:17:00 ][INFO]: Released wave file resources
[ 2018-02-05 15:17:00 ][INFO]: Audio transcoding. Source file name ==================> : C:\Users\dmorgan\Desktop\Unity\parametricdesign\Gallery/movie_2048x1024_2018-02-05 03_16_57.wav
[ 2018-02-05 15:17:00 ][ERROR]: Failed to set pcm media type. [Error code] : -2147024809

**Comment by grancia** [comment]
Can you try with "attachedHMD = VRDeviceType.UNKNOWN " by force in void Start() of surroundCapture.cs or NonSurroundCapture.cs ?

**Comment by haitheredavid** [comment]
no luck... 

[ 2018-02-05 17:35:23 ][INFO]: Folder is already existed
[ 2018-02-05 17:35:23 ][INFO]: WAV file name ==================> : C:\Users\dmorgan\Desktop\Unity\parametricdesign\Gallery/movie_2048x1024_2018-02-05 05_35_23.wav
[ 2018-02-05 17:35:23 ][INFO]: Set encode configurations successfully
[ 2018-02-05 17:35:23 ][INFO]: No data can be read from Microphone--IAudioCaptureClient::GetBuffer
[ 2018-02-05 17:35:27 ][INFO]: Released wave file resources
[ 2018-02-05 17:35:27 ][INFO]: Audio transcoding. Source file name ==================> : C:\Users\dmorgan\Desktop\Unity\parametricdesign\Gallery/movie_2048x1024_2018-02-05 05_35_23.wav
[ 2018-02-05 17:35:27 ][ERROR]: Failed to set pcm media type. [Error code] : -2147024809

**Comment by grancia** [comment]
what if you try with useVRAudioResources: false in audioEncoding of SurroundCapture.cs or NonSurroundCapture.cs like below?

audioEncoding(useVRAudioResources: false, silenceMode: pauseAudioCapture, VRDeviceType.UNKNOWN, useMicIMMDeviceId: null);

**Comment by haitheredavid** [comment]
Gave that a shot, and it didn't seem to do the trick... I also tried commenting out the muxing and audio lines in Nonsurriound and Surround last night in order to by-pass any audio issues. 

   if (muxingthread == null)
            {
                muxingthread = new thread(muxingthread);
                muxingthread.start();
            }

            if (audioThread == null)
            {
                audioThread = new Thread(AudioThread);
                audioThread.Start();
            }

**Comment by grancia** [comment]
No it's wrong approach...  it's odd... 
Can you check following thread? It might fix your issue... 
https://github.com/facebook/360-Capture-SDK/issues/32
