### ISSUE TITLE
No clear support for Unreal Engine

### ISSUE THREAD

**Issue by pekayatt** [facebook/360-Capture-SDK#34]
At the beginning of the description of the plugin it is said that it supports Unreal Engine.

Nevertheless, at the "How to integrate" section there is not clear instructions how to use it with Unreal Engine.

**Comment by grancia** [comment]
We don't have Unreal integration sample yet. That means you will need to integrate by yourself for now like native engine integration. 
But we're planing to provide unreal and native engine integration sample soon. 
Thanks!

**Comment by pekayatt** [comment]
Thanks for the fast reply, should I close this or leave it open for when we get the integration sample?

**Comment by grancia** [comment]
it's up to you :)
