### ISSUE TITLE
integration in other Apps

### ISSUE THREAD

**Issue by jimpanse90** [facebook/360-Capture-SDK#35]
Hi there,

Thanks for all your work and support! I have one short question. Is it possible to integrate this into Facebook Spaces? I would like to record 360° of a conversation in order to get a video file that i can upload on youtube and see in 360°. Unfortunately, spaces lets you only record and stream in "flat" mode

thanks for your help,
Chris

**Comment by grancia** [comment]
Actually Facebook Spaces team has adopted this capture SDK, but they only use it as flat mode for now. 
If they want to extend live streaming to 360, they can do anytime, but dev team should enable it. You can't do that.
