### ISSUE TITLE
Video Pauses During Encoding

### ISSUE THREAD

**Issue by cieraej** [facebook/360-Capture-SDK#37]
Hi, 

I am using Unity 2017.4.0f1 and Windows 10. The encoder works for about 9 seconds before it just video pauses, and it doesn't say that there's an error. What can I do to ensure that this does not happen?

Best, 
Ciera

**Comment by grancia** [comment]
Can you share FBCaptureSDK.txt in your project folder?

**Comment by cieraej** [comment]
[FBCaptureSDK.txt](https://github.com/facebook/360-Capture-SDK/files/1904913/FBCaptureSDK.txt)

Thank you for getting back to me so quickly!
It currently doesn't put out any errors pertaining to the issue. The only errors in this file are when I was trying to push it to an 8k video file.

**Comment by cg439** [comment]
Can you specify more details about your pc, os, gfx card, the resolution
and context of what you are encoding? Anything above 4k breaks currently
from encoding POV.

**Comment by grancia** [comment]
I can't download your attached log file. Can you just copy and paste here?
Also as cg439 said, we don't support more than 4k encoding by limitation from AMD and NVIDIA's hardware encoding APIs.

**Comment by cieraej** [comment]
pc: AMD Ryzen 51600
os: Windows 10
gfx card: NVIDIA GTX 1070 Ti
resolution: 4096 x 2048 & 2048 x 1024
and context of what you are encoding? encoding a unity scene using the encoder object provided/ 
video example: [https://vimeo.com/264512278](https://vimeo.com/264512278)

The log file : 
[ 2018-04-12 17:11:48 ]: Capture SDK Version: : 1.20
[ 2018-04-12 17:11:49 ][INFO]: Output folder already existed
[ 2018-04-12 17:11:49 ][INFO]: It's invalid texture pointer: null
[ 2018-04-12 17:11:49 ][INFO]: WAV file name ==================> : D:\Unity Projects\MakingWater_ClinkenFilms\MakingWater\Gallery/movie_2048x1024_2018-04-12 05_11_49.wav
[ 2018-04-12 17:12:00 ][INFO]: Released wave file resources
[ 2018-04-12 17:12:00 ][INFO]: Audio transcoding. Source file name ==================> : D:\Unity Projects\MakingWater_ClinkenFilms\MakingWater\Gallery/movie_2048x1024_2018-04-12 05_11_49.wav

(this log file hasn't updated anything since i stopped trying to make 8k videos) 

Let me know if you need anything else to help diagnose the problem!

**Comment by grancia** [comment]
That issue seems to be what I fixed few weeks ago.
Since we're preparing for releasing 2.0 soon, I didn't update current version for a while. 
But for your test, I will update latest version of 1.0 today. If you still encounter the issue, please let me know.
Thanks,

**Comment by cieraej** [comment]
Amazing! 

Thank you so much for the time spent on helping me fix this issue! It is very much appreciated :) 
Will update you on whether the fix is successful. 

Best, 
Ciera

**Comment by cieraej** [comment]
It is still doing it! The only way I can make it a bit better is by reducing the complexity of the scene. But it isn't too intensive as is. I will try to see if dropping to the version of Unity you're using might help? Do you have any other suggestions?

**Comment by cg439** [comment]
Is the core issue that the GPU can't handle rendering the scene or that it
cannot encode it? One way to test this would be to pick a very simple scene
and then try encoding that content at a high resolution like 3840x1920 as a
360 or 4096x2048. After that try cranking up scene complexity and see if it
works for you. Are your drivers up to date for Nvidia?

**Comment by grancia** [comment]
I think you're already rendering heavy scene? Because of that, it seems like GPU doesn't have enough room for encoding work.
Can you grab the latest code that I just pushed and try with lower "fps" value on CaptureOption?(like 30 fps to 24 fps)
And as Chetan said, if you're using old graphics card, then you need to update the driver too. 

https://github.com/facebook/360-Capture-SDK/commit/c093af074fcca083994acd39f0347992ac43d9e1
