### ISSUE TITLE
Video missing frames

### ISSUE THREAD

**Issue by psychicteeth** [facebook/360-Capture-SDK#39]
Hi! This is a wonderful SDK! Thank you!

We are having a problem, though. We're trying to record video very fast by disabling vsync and running Unity in fixed frame rate mode. 

We do this by setting GraphicsSettings.vSyncCount to 0 and setting Time.captureFramerate to the desired FPS of the output video. This enables the app to process frames at a much faster rate than real time. However, the resulting video comes out way shorter and faster than expected and only records every 3rd frame for a 60fps video, resulting in a video that is something like 2.5s-3s long instead of 10s.

This is unexpected behaviour - I assumed that setting FBCaptureSDK.vodVideoFrameRate to 60 would result in a 60fps video that contained every frame we threw at it.

Is there something we are doing wrong here, or is it a bug? 

If it's in a thread, is it possible that the thread is still processing a previous frame when we try to send a new capture? 

Is there some way we can block the main thread and wait for the encoding thread to finish processing a previous frame before sending a new capture?

**Comment by grancia** [comment]
If you set FBCaptureSDK.vodVideoFrameRate to 60 fps, capture sdk will expect to get 60 textures per second for making 60 fps videos, but in your case, it seems like it can't pass 60 textures per sec to sdk side. What's your current resolution setting? And what's your graphics card? Can you try with lower resolutions? 
I think you can still use "vodVideoFrameRate = 30" with your settings for GraphicsSettings.vSyncCount and Time.captureFramerate for your purpose though.

**Comment by grancia** [comment]
Hi,
Basically, we're managing fps in encoding thread in FBCapture.dll and textures are totally encoded based on fps setting with timer function. For example, if we set fps to 30, then we're handling texture encode every 1/30 secs. Yes, SDK is not expecting to receive frames more frequently than the FPS set. 
Your case seems to be edge case... I would recommend you to play with source code for custom.
Thanks,

**Comment by psychicteeth** [comment]
Hey, thanks for the reply! I see you've added c++ source to the repo, that's awesome! I'll have a look. Thanks!
