### ISSUE TITLE
Photos output, videos do not

### ISSUE THREAD

**Issue by mateicanavra** [facebook/360-Capture-SDK#4]
Just started playing around with this, and I've come across an issue with outputting and saving video:

I am able to take both rectilinear and equirectangular screenshots and save to the absolute path. However, when I try to capture video (in either non-surround or surround), no file is found in the output folder. I did not change the absolute path.

Is there a step in the process that I'm missing? Could it have something to do with my GPU (NVIDIA GeForce GTX 960M)?

**Comment by grancia** [comment]
Can you check 360Capture_log.txt file? What errors can you see there?
If it failed in initialization, you will need to update graphics driver.
As noted in readme,  NVidia Windows display driver should be 375.95 or newer.

**Comment by mateicanavra** [comment]
Excellent, I will check today, thanks

**Comment by mateicanavra** [comment]
Updating my graphics driver and reimporting all assets did the trick. Thanks!
