### ISSUE TITLE
NV_ENC_ERR_OUT_OF_MEMORY

### ISSUE THREAD

**Issue by 807183087** [facebook/360-Capture-SDK#43]
I found when I record once ,the function "NvEncOpenEncodeSessionEx(device, deviceType)" was invoked twice. 
1、FBCaptureSystem::getCaptureCapability()   ->
      EncoderMain::initSessionANDdriverCapabilityCheck()   ->
      "status = this->nvEncoder->initNVEncodingSession();
2、BCaptureSystem::encodeThreadRun()  ->
      EncoderMain::startEncoding  -> 
      FBCAPTURE_STATUS NVEncoder::encodeMain  ->
      “status = initNVEncodingSession();”
This make two NV session ,but only release one after stop record, is not it?
And when I record continuously ,the issue occured with NV_ENC_ERR_OUT_OF_MEMORY.

**Comment by grancia** [comment]
Hi!
The m_pEncodeAPI is created once at init and doesn't create another encoding session unless m_pEncodeAPI is  nullptr. And we've tested bunch of times for recording and live streaming on our side and qa team before releasing it, but haven't seen the issue before.

Do you have full log of capture sdk which is located in "%LOCALAPPDATA%\FBCapture\FBCaptureSDK.txt"?

**Comment by 807183087** [comment]
Thank you for reply. It is my
