### ISSUE TITLE
Compiling the source

### ISSUE THREAD

**Issue by psychicteeth** [facebook/360-Capture-SDK#44]
Hi again!

I'm trying to compile the DLL from source, but having some trouble as VS complains that some of the static libs are compiled with an old compiler, and it wants me to rebuild them. Since source for some of the libs isn't in the repo, would it be possible to identify a location for those? The only one I haven't found so far is the mp4muxer in wamedia, but also have a feeling the flvoperations.lib I compiled is wrong as the original is 19 megabytes and my compiled version is 32k :)

**Comment by psychicteeth** [comment]
Hey, yes I did, thank you for uploading them! It's just that the wamedia zip only contains libs and headers, and I can't rebuild the libs from that. VS is complaining that the libs are out of date and must be recompiled. Alternatively I could start again using an older compiler - what are you folks using to compile the fbcapture dll?

**Comment by grancia** [comment]
It's interesting... I don't see any problem here on build. We're using Visual Studio Enterprise 2015.

**Comment by psychicteeth** [comment]
Nice, thanks! I'll install the correct build tools - looks like I need these ones: https://www.microsoft.com/en-us/download/details.aspx?id=48159

**Comment by psychicteeth** [comment]
Ah you can do it from the extensions manager in visual studio 2017. OK, closing this!
