### ISSUE TITLE
Only record sound

### ISSUE THREAD

**Issue by fresh08** [facebook/360-Capture-SDK#5]
Hello:

        Is it possible to record only the sound, and sometimes I do not need a video.

Best reards!

**Comment by cg439** [comment]
You can look at the Unity implementation to try to call the API to just record audio and write the .AAC file. We do not currently support conversion of the AAC format to an mp4, but it may work if you avoid specifying a video file to the muxer so it outputs an mp4 with no video and just audio

**Comment by grancia** [comment]
Because it has been about over two months since v2.0 was released, I want to close v1.x related issues now. If you have any issue on v2.0, please create separate thread. 
Thanks,
