### ISSUE TITLE
Capture with Unity & Sample SteamVR scene

### ISSUE THREAD

**Issue by vonengel3d** [facebook/360-Capture-SDK#52]
Hi everybody,

I found your project for 360-degree image & video capture. I followed the user guide for integrating it into the sample SteamVR unity scene. Unfortunately, I'm getting these errors when trying to record a screenshor or a video:

[ 2018-09-04 08:30:26 ][INFO] Capture SDK Version: : 2.0
[ 2018-09-04 08:30:26 ][INFO] Graphics Card Info: : NVIDIA Quadro M2000M
[ 2018-09-04 08:30:26 ][INFO] Graphics Card Info: : Intel(R) Iris(TM) Pro Graphics P580
[ 2018-09-04 08:30:26 ][INFO] Graphics Card Info: : Microsoft Basic Render Driver
[ 2018-09-04 08:30:26 ][INFO] Output folder already existed
[ 2018-09-04 08:30:26 ][INFO] Passed capture capability tests. Ready to start encoding
[ 2018-09-04 08:30:26 ][INFO] Output folder already existed
[ 2018-09-04 08:30:26 ][INFO] Added metadata for 360 recognition in FB
[ 2018-09-04 08:30:27 ][INFO] Failed to map resources
[ 2018-09-04 08:30:27 ][ERROR] Failed on creating image file. [Error code] : -2005270523
[ 2018-09-04 08:30:27 ][ERROR] Failed on screenshot: 112
[ 2018-09-04 08:30:29 ][ERROR] Failed to create screenshot Texture2D FBCaptureSystem. [Error code] : -2005270523
[ 2018-09-04 08:30:39 ][ERROR] Failed to create encoding Texture2D FBCaptureSystem. [Error code] : -2005270523
[ 2018-09-04 08:30:41 ][ERROR] Failed to create encoding Texture2D FBCaptureSystem. [Error code] : -2005270523

Do I have do to something special to use the lib with a VR device? Your sample unity scene works for me.

Thanks,
David

**Comment by vonengel3d** [comment]
I did a new pull and I don't see this error anymore. However, I can only record videos and no screenshots.
The resulting jpg file of the screenshot is either blank or sometimes it contains the equirectangular image and is partly override by a non 360 degree screenshot of the scene.

FYI: I played around with the various options (RGB, RGBD) options, I ended up getting one correct 360 degree screenshot. I did not change the options and triggered the screenshot creation a second time and got a corrupted one again.

**Comment by grancia** [comment]
Have you pulled Unity sample as well? 
Could you please make sure you're generating render texture with 24bit depth here?
https://github.com/facebook/360-Capture-SDK/blob/master/Samples/Unity/Assets/FBCAPTURE/Scripts/FBCaptureSDK.cs#L1155

I would recommend you also pulling unity sample and applying the scripts and prefab to your project.

**Comment by vonengel3d** [comment]
I did pull the Unity sample as well and also did not change the FBCaptureSDK script.
I copied the folder "FBCAPTURE" into my project. Somehow capturing a 360 degree screenshot sometimes works and sometimes I only get a blank jpg. Capturing a 360 degree video always works for me.

I'm using Unity 2018.2.0f2. Did you try running your lib with the sample scene that comes with the steamvr unity asset?

**Comment by grancia** [comment]
I can repro your issue here. I will fix it and push changes this week.

**Comment by grancia** [comment]
I just updated new version fixing your issue. Please pull latest and test.
Thanks, 

https://github.com/facebook/360-Capture-SDK/releases/tag/v2.25

**Comment by vonengel3d** [comment]
The new version works for me. Thanks for the quick fix.
