### ISSUE TITLE
Save WAV FILE

### ISSUE THREAD

**Issue by fresh08** [facebook/360-Capture-SDK#6]
Hi~ o(*￣▽￣*)ブ：
I see it generate a encodedAudio.wav file when recording, can I get this file and renamed at run time? Or can provide an interface to record only this wav file, and can customize the file name.

**Comment by grancia** [comment]
Sound is captured with wav format and transcoded to aac, and then it muxes with video. But we're deleting all files except final video file. I haven't checked asset store yet, but I guess you can find audio capture plugin there.

**Comment by grancia** [comment]
Because it has been about over two months since v2.0 was released, I want to close v1.x related issues now. If you have any issue on v2.0, please create separate thread. 
Thanks,
