### ISSUE TITLE
Update meta data to support 360 video playback on FB, YouTube etc.

### ISSUE THREAD

**Issue by hhprg** [facebook/360-Capture-SDK#7]
Would be great if the captured 360 surround video file would include meta data to support 360 video playback in FB, YouTube etc.

As described here:
https://support.google.com/youtube/answer/6178631?hl=en

**Comment by grancia** [comment]
Thank you for your feedback.
Now we're working on it.

**Comment by cg439** [comment]
I think this should be added at the moment, need to double check if it's in main branch or experimental

**Comment by grancia** [comment]
It's up in V2.0. Please grab latest version.
Thanks,
